# Unique key for your project
sonar.projectKey=CBRS503

# Friendly project name
sonar.projectName=CBRS503

# Project version
sonar.projectVersion=1.0

# Source code folder (dot = current folder)
sonar.sources=.

# Optional: test folder (if any)
# sonar.tests=tests

# Source file encoding
sonar.sourceEncoding=UTF-8

# Local SonarQube URL
sonar.host.url=http://localhost:9000

# Authentication token from SonarQube
sonar.login=squ_24a692d4e959b83ba42d601c44fa3054454d6d41