from docx import Document
from docx.shared import Inches, Pt
import matplotlib.pyplot as plt
from datetime import datetime
from collections import Counter

def create_advanced_vuln_report(summary: dict, results: dict, output_file: str):
    """
    Generate an advanced OWASP vulnerability report.
    
    summary: {file_path: count} for summary table & chart
    results: {file_path: [OWASPVulnerability objects]} for detailed findings
    """
    
    doc = Document()
    
    # Set document font globally
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)
    
    # -----------------------------
    # Cover Page
    # -----------------------------
    doc.add_heading("Security Vulnerability Report", 0)
    doc.add_paragraph("Generated by Automated OWASP Code Analysis Tool", style='Intense Quote')
    doc.add_paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    doc.add_paragraph(f"Total Vulnerabilities Detected: {sum(summary.values())}")
    doc.add_paragraph("Confidential – For Internal Use Only")
    

    
    # -----------------------------
    # Executive Summary
    # -----------------------------
    doc.add_heading("Executive Summary", level=1)
    
    total_vulns = sum(summary.values())
    num_files = len(summary)
    
    # Risk levels
    all_vulns = [v for vulns in results.values() for v in vulns]
    risk_counts = Counter(getattr(v, "risk_level", "Unknown") for v in all_vulns)
    
    doc.add_paragraph(
        f"A total of {total_vulns} vulnerabilities were identified across {num_files} files.\n"
        f"Risk distribution: Critical={risk_counts.get('Critical',0)}, "
        f"High={risk_counts.get('High',0)}, Medium={risk_counts.get('Medium',0)}, "
        f"Low={risk_counts.get('Low',0)}.\n"
        "Immediate remediation is recommended for all Critical and High risks."
    )
    

    
    # -----------------------------
    # Summary Table
    # -----------------------------
    doc.add_heading("Summary Table", level=1)
    
    table = doc.add_table(rows=1, cols=3)
    table.style = 'Medium Shading 1 Accent 1'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = "File"
    hdr_cells[1].text = "# Vulnerabilities"
    hdr_cells[2].text = "Highest Risk"
    
    for file, count in summary.items():
        row_cells = table.add_row().cells
        row_cells[0].text = file
        row_cells[1].text = str(count)
        # Determine highest risk for the file
        file_vulns = results.get(file, [])
        if file_vulns:
            risks = [getattr(v, "risk_level", "Unknown") for v in file_vulns]
            row_cells[2].text = sorted(risks, key=lambda x: ['Critical','High','Medium','Low','Unknown'].index(x))[0]
        else:
            row_cells[2].text = "None"
    
    # -----------------------------
    # Charts
    # -----------------------------
    files = list(summary.keys())
    counts = list(summary.values())
    
    # Bar chart
    plt.figure(figsize=(10, 5))
    plt.barh(files, counts, color='tomato')
    plt.xlabel("Number of Vulnerabilities")
    plt.title("Vulnerabilities per File")
    plt.tight_layout()
    chart_path = "vuln_bar_chart.png"
    plt.savefig(chart_path)
    plt.close()
    doc.add_picture(chart_path, width=Inches(6))
    
    # Pie chart by risk
    if all_vulns:
        labels = risk_counts.keys()
        sizes = risk_counts.values()
        plt.figure(figsize=(6,6))
        plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140, colors=['red','orange','yellow','green'])
        plt.title("Vulnerability Risk Distribution")
        plt.tight_layout()
        pie_path = "vuln_risk_pie.png"
        plt.savefig(pie_path)
        plt.close()
        doc.add_picture(pie_path, width=Inches(4))
    

    
    # -----------------------------
    # Detailed Findings
    # -----------------------------
    doc.add_heading("Detailed Findings", level=1)
    
    for file_path, vulnerabilities in results.items():
        doc.add_heading(f"File: {file_path}", level=2)
        if not vulnerabilities:
            doc.add_paragraph("No OWASP Top-10 vulnerabilities found.")
            continue
        
        for vuln in vulnerabilities:
            owasp_id = getattr(vuln, "owasp_id", "")
            name = getattr(vuln, "name", "")
            description = getattr(vuln, "description", "")
            evidence = getattr(vuln, "evidence", "")
            steps = getattr(vuln, "exploitation_steps", [])
            impact = getattr(vuln, "impact", "")
            mitigation = getattr(vuln, "mitigation", "")
            risk = getattr(vuln, "risk_level", "Unknown")
            
            heading = doc.add_heading(f"{owasp_id} — {name} [{risk}]", level=3)
            
            # Highlight Critical/High risks
            if risk in ['Critical', 'High']:
                run = heading.runs[0]
                run.font.color.rgb = (255,0,0)
            
            doc.add_paragraph().add_run("Description: ").bold = True
            doc.add_paragraph(description)
            
            doc.add_paragraph().add_run("Evidence: ").bold = True
            doc.add_paragraph(evidence)
            
            if steps:
                doc.add_paragraph().add_run("Exploitation Steps:").bold = True
                for step in steps:
                    doc.add_paragraph(step, style="List Bullet")
            
            doc.add_paragraph().add_run("Impact: ").bold = True
            doc.add_paragraph(impact)
            
            doc.add_paragraph().add_run("Mitigation: ").bold = True
            doc.add_paragraph(mitigation)
            
            # Add OWASP link
            doc.add_paragraph(f"For more info, visit: https://owasp.org/www-project-top-ten/{owasp_id.lower()}")
    

    
    # -----------------------------
    # Overall Recommendations
    # -----------------------------
    doc.add_heading("Overall Recommendations", level=1)
    doc.add_paragraph(
        "• Prioritize remediation of Critical and High vulnerabilities.\n"
        "• Remove hardcoded secrets immediately.\n"
        "• Implement input validation and use parameterized queries.\n"
        "• Conduct secure code reviews and regular scanning.\n"
        "• Integrate automated security testing into CI/CD pipelines."
    )
    
    # -----------------------------
    # Appendix / Glossary
    # -----------------------------
    doc.add_heading("Appendix / Glossary", level=1)
    doc.add_paragraph(
        "OWASP Top-10: A standard awareness document for developers and security experts, representing the most critical web application security risks.\n"
        "Risk Levels: Critical, High, Medium, Low, Unknown.\n"
        "CI/CD: Continuous Integration / Continuous Deployment pipeline."
    )
    
    # -----------------------------
    # Save Document
    # -----------------------------
    doc.save(output_file)
    print(f"Report generated: {output_file}")
