name: Simple CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install tools
        run: pip install pytest flake8 bandit

      - name: Lint
        run: flake8 . --max-line-length=300 --ignore=W291,W293

      - name: Security Scan
        run: bandit -r .

      - name: Run Tests
        run: pytest || echo "No tests found"
